name: censura
main: com.craftcostaserver.jailrules.censura.Censura
version: 0.1
description: Plugin de castigos
depend: [Essentials]
commands:
  censura:
    description: Usa /censura help para obtener ayuda
    usage: /<command> o /<command> help
  cjail:
    description: Usa /cjail para encarcelar a un jugador
    usage: /<command> <jugador> <celda> <tiempo> <razon>
  cunjail:
    description: Usa /cjail para desencarcelar a un jugador
    usage: /<command> <jugador> <razon>
  ckick:
    description: Usa /ckick para kickear a un jugador
    usage: /<command> <jugador> <razon>
  ctempban:
    description: Usa /ctempban para banear temporalmente a un jugador
    usage: /<command> <jugador> <tiempo> <razon>
  cban:
    description: Usa /cban para banear a un jugador
    usage: /<command> <jugador> <razon>
  cunban:
    description: Usa /cunban para desbanear a un jugador
    usage: /<command> <jugador> <razon>
  cmute:
    description: Usa /cmute para mutear a un jugador
    usage: /<command> <jugador> <razon>
  ctempmute:
    description: Usa /ctempmute para mutear temporalmente a un jugador
    usage: /<command> <jugador> <tiempo> <razon>
  cunmute:
    description: Usa /cjail para desmutear a un jugador
    usage: /<command> <jugador> <razon>
  cwarn:
    description: Usa /cwarn para advertir a un jugador
    usage: /<command> <jugador> <razon>
  cjailmute:
    description: Usa /cjailmute para encarcelar y mutear temporalmente a un jugador
    usage: /<command> <jugador> <celda> <tiempo> <razon>
  cunjailmute:
    description: Usa /cjailmute para encarcelar y mutear temporalmente a un jugador
    usage: /<command> <jugador> <razon>
  cphistory:
    description: Usa /cphistory para ver el historial de castigos de un jugador
    usage: /<command> <jugador> <pagina>
  chistory:
    description: Usa /chistory para mostrar el historial de castigos
    usage: /<command> <pagina>
  cpurge:
    description: Usa /cpurge para purgar los registros de la base de datos
    usage: /<command> <dias>
  cppurge:
    description: Usa /cppuerge para purgar los registro de un usuario concreto
    usage: /<command> <jugador>
  

permissions:
  censura.*:
    description: Give players with op everything by default with DDBB manage
    children:
      censura.admin: true
  censura.admin:
    description: Give players with admin ban unban by default and all sacntions
    children:
      censura.mod: true
  censura.mod:
    description: Give players with mod rest of sanctions by default
    default: op
